---
- name: copy file
  hosts: all
  tasks:
  - name: copy dockerfile
    copy:
       src: /home/ansible/Dockerfile
       dest: /home/ansible
       mode: 0644
  - name: add user
    user:
      name: jp
      state: present
