---
- name: test playbook
  hosts: all
  become: true
  tasks:
  - name: test
    apt:
      name: apache2
      state: present
   - name: service 
     service:
       name: apache2
       state: restarted
   - name: service
     service:
       name: apache2
       enabled: yes
